### PR TITLE
feat: updated openocd shared files

### PR DESCRIPTION
**Pull request by Waaflee**

### CODE REVIEW

**Comment by Waaflee** [comment]
Added shared libraries needed for openocd to work. Now its not needed to have openocd installed on system

**Comment by Wiz-IO** [comment]
picoprobe ( executable ) permitions is set?
tommorow will update...

**Comment by e2forlife** [comment]
Checked out and ran debug session with my project.  Produces a segmentation fault and core dump
```
Reading symbols from /home/<user>/Documents/Projects/Deimos/.pio/build/raspberry-pi-pico/APPLICATION.elf...
done.
PlatformIO Unified Debugger -> https://bit.ly/pio-debug
PlatformIO: debug_tool = picoprobe
PlatformIO: Initializing remote target...
Segmentation fault (core dumped)
.pioinit:13: Error in sourced command file:
Remote communication error.  Target disconnected.: Connection reset by peer.
```

**Comment by Wiz-IO** [comment]
updated with pull

**Pull request merged**
